### ISSUE TITLE
Please deploy the working version of the app!

### ISSUE THREAD

**Issue by Dynkin** [malilfrend/weatherReactApp#2]
Now only GH Pages verison is deployed and it is not working correctly. It would be nice if you add the link to working version of the app to the project description!

**Comment by malilfrend** [comment]
Done

**Comment by Dynkin** [comment]
And this looks super cool! Congratulations!

**Comment by malilfrend** [comment]
Thanks for your help with server on express. I really appreciate that)

**Comment by Dynkin** [comment]
No problem! 😎
